### ISSUE TITLE
Send Token & Swap Token Agent Benchmark

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/AutoTx#101]
Create a multi-agent benchmark that uses the `SendToken` and `SwapToken` agents in tandem. The prompts should be sufficiently complex leading to 2+ tasks within the agent's execution plan.

**Comment by nerfZael** [comment]
We the introduction of autogen (https://github.com/polywrap/AutoTx/pull/142) and tests are passing more consistently although the send and swap complex test is at 50%
@dOrgJelli should we close this and open a new one for that case?

**Comment by dOrgJelli** [comment]
Let's move this work to #166
