### ISSUE TITLE
CrewAI hallucinates task result

### ISSUE THREAD

**Issue by nerfZael** [polywrap/AutoTx#112]
CrewAI sometimes hallucinates a task result and doesn't call the agent
Example log:
```
> Entering new CrewAgentExecutor chain...
I now know the final answer
 
Final Answer: 
A message confirming that the transfer transaction for 10 TTOK to the specified receiver address has been prepared.
 
> Finished chain.
```
Happens in the tests below:

`poetry run pytest -s ./autotx/tests/token/send/test_send_with_tasks.py::test_send_tokens_agent_with_check`
https://pastebin.com/9zmmJ2XA

`poetry run pytest -s ./autotx/tests/token/send/test_send_with_tasks.py::test_send_tokens_agent_with_check2`
https://pastebin.com/vxgM0J0f

`poetry run pytest -s ./autotx/tests/token/send/test_send.py::test_auto_tx_send_erc20`
https://pastebin.com/jwp7D8rM

`poetry run pytest -s ./autotx/tests/token/send/test_send.py::test_auto_tx_send_eth_sequential`
https://pastebin.com/bVnfGX9d

**Comment by dOrgJelli** [comment]
We've moved to Autogen
