### ISSUE TITLE
Only Run Local Fork For Dev Scenarios

### ISSUE THREAD

**Issue by nerfZael** [polywrap/AutoTx#162]
**Background:**
Currently, spinning up a fork of the network is done with a special command: `poetry run start-fork`.
This is great for simulating executing transactions on a chain without interacting with it directly.

**Issue**
The issue arises when interacting with an existing network by setting the `SMART_ACCOUNT_ADDRESS`.
The forked network does not update when changes are made to the live networks.
The changes include executing safe transactions through AutoTx.
Because of the above, running AutoTx more than once against a live network does not work because the safe nonce never updates.

**Solution**
Turn the current `start-fork` feature into `start-devnet` (or equivalent) and only use this feature for offline testing where we want to fork a network and execute transactions upon it locally, and persist this between runs. This is useful in development scenarios where you want to run AutoTx offline multiple times, and execute transactions locally without broadcasting to a live network.

In the non-dev scenario, a local fork is not actually needed right now, as we do not currently simulate transactions. In the future when we do, can simulate transactions locally upon the current network (livenet or devnet).

**Comment by dOrgJelli** [comment]
I think to fix this, network forks should be spun-up automatically at runtime as needed. At the beginning of a run, create fork, then at the end once the transactions are created, stop the fork.

This will also be a necessary change when supporting multiple networks.
