### ISSUE TITLE
Gnosis Chain Support

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/AutoTx#230]
Currently we do not properly support Gnosis Chain as our uniswap integration does not have a subgraph for this chain: https://github.com/polywrap/AutoTx/blob/main/autotx/utils/ethereum/uniswap/swap.py

Let's use this thread to track individual tasks needed to be done to properly support Gnosis Chain.

**Comment by cbrzn** [comment]
that's because uniswap is not deployed in gnosis chain, to fix this, i'd propose we follow path proposed in https://github.com/polywrap/AutoTx/issues/222

**Comment by dOrgJelli** [comment]
Sounds great, agreed. Also it's worth noting that even simple use-cases like "send 1 ETH to vitalik.eth" do not work.
