### ISSUE TITLE
Transaction creation for swap from ERC20 fails with smart account connected

### ISSUE THREAD

**Issue by cbrzn** [polywrap/AutoTx#240]
When smart account is connected, the transaction is posted to the transaction service API. When this happens, [the transaction gas is calculated](https://github.com/polywrap/AutoTx/blob/main/autotx/utils/ethereum/SafeManager.py#L156-L157) making the swap transaction fail because it needs the allowance of the amount to be swap

**Comment by nerfZael** [comment]
Closing this since it's fixed
