### ISSUE TITLE
Researcher agent should do research instead of user_proxy

### ISSUE THREAD

**Issue by nerfZael** [polywrap/AutoTx#244]
Right now with all of the researcher prompts, the user_proxy plans the research strategy and all the researcher does is call its functions.
This makes it hard to prompt engineer since we would have to give the user_proxy knowledge about token research which should really be reserved for the researcher agent.

This is a bigger issue and likely requires an architecture shift towards nested chats.
Nested chats come with their own set of problems like we discovered with evo.ninja.
The biggest one is: agent A passing context into agent B often leaves out important info or changes details.

**Comment by dOrgJelli** [comment]
Very interesting. Is there an easy way to "fork" a chat's context? If so we could fork the root, and run a research specific agent loop.

**Comment by dOrgJelli** [comment]
Also one way to solve this is to group all token functionality into a "token" domain, and we can more easily provide detailed system prompts there that help solve for situations like this.
