### ISSUE TITLE
Tracking usage analytics

### ISSUE THREAD

**Issue by rihp** [polywrap/AutoTx#40]
For projects like evo ninja where we have a web based UI we can install google analytics to track usage.

However, evo ninja is our current only benchmark with analytics installed.

How can we track usage statistics? Maybe pip package downloads?

**Comment by dOrgJelli** [comment]
Currently our primary metrics are:
* GitHub repo stars
* New contributors
* GitHub repo views
* GitHub repo forks
* package downloads (once published)

**Comment by dOrgJelli** [comment]
Going to close this as there's no development work needed for this.
