### ISSUE TITLE
Improve prompt to execution plan

### ISSUE THREAD

**Issue by cbrzn** [polywrap/AutoTx#54]
The [plan creation](https://github.com/polywrap/AutoTx/blob/main/autotx/AutoTx.py#L34) sometimes doesn't add the needed information  for the action to be executed, hence, making the execution agent lack context

If we pass a complex prompt like "Swap ETH to 0.05 WBTC, then, swap WBTC to 1000 USDC and send 50 USDC to 0x10f8Bf6a479F320ead074411A4b0e7944eA8C9c1", the tasks are consistently not correct; it should explicitly buy 1000 USDC in the second step, rather than selling an amount of WBTC

we should have an "evaluation" step where we ensure that the tasks are correct and make sense with what has been told in the prompt

**Comment by dOrgJelli** [comment]
This issue is being tracked here: https://github.com/polywrap/AutoTx/issues/101
