### ISSUE TITLE
Better debug `GS013` from safe transactions

### ISSUE THREAD

**Issue by cbrzn** [polywrap/AutoTx#55]
The agent may create bad transactions (by passing wrong input/because of wrong calldata formed/an error at contract level like the need of approval before swap). When this happens, transaction execution returns an [GS013](https://github.com/safe-global/safe-smart-account/blob/v1.3.0/contracts/GnosisSafe.sol#L176-L180) error because the [`execute`](https://github.com/safe-global/safe-smart-account/blob/v1.3.0/contracts/base/Executor.sol#L8) method failed.

Right now, we do not have error propagation from these transactions, we should simulate them somehow so we (and the agent) can know what's happening

**Comment by nerfZael** [comment]
I think this is most likely solved (and at minimum hasn't happened again) since #74 , so I'm closing it for now
