### ISSUE TITLE
Run fails because `.cache` directory doesn't exist

### ISSUE THREAD

**Issue by kongzii** [polywrap/AutoTx#81]
The first run fails because the `.cache` directory doesn't exist in https://github.com/polywrap/AutoTx/blob/4037c1030a15c872c7a63f422c7cc8b342f5c835/autotx/utils/ethereum/agent_account.py#L17

so it needs to be created manually and then it's okay.

It's not a big issue, but it could provide a better first-time experience.

Probably related to https://github.com/polywrap/AutoTx/issues/80, as `cache` function implements this: https://github.com/polywrap/AutoTx/blob/4b993cffa420a59aa2484ff2fffe19bcb63d9901/autotx/utils/ethereum/cache.py#L14

**Comment by cbrzn** [comment]
hey @kongzii thanks for opening this :smile: i tried to reproduce but wasn't able, do you have some reproducible steps? for context, what i did:
- cloned the repo (to start from scratch)
- ran `poetry run start-fork`
- ran `poetry run ask --prompt="send 0.1 eth to 0xAC39C85F4E54797e4909f70a302d9e11E428135D"`
