### ISSUE TITLE
Discount ETH for gas when sending or swapping tokens

### ISSUE THREAD

**Issue by nerfZael** [polywrap/AutoTx#90]
If the user tells the agent to send ALL ETH or swap ALL ETH then the transaction will fail because there will not be enough to pay for it.
We need to discount the amount needed to cover gas either automatically, or inform the user somehow

Example:
` poetry run ask --prompt "Buy me as much USDC as possible with ETH"`

**Comment by dOrgJelli** [comment]
Since smart accounts (ex: safe) can have their transactions executed via a 3rd party paying for gas, I think this isn't an issue we need to focus on solving.
